<center><img src="img/logo_hse_black.jpg"></center>

<h1><center>Data Analysis</center></h1>
<h2><center>Seminar: Ensemble Learning. </center></h2>

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read Data

In [2]:
#dataset from here https://archive.ics.uci.edu/ml/datasets/Epileptic+Seizure+Recognition
df = pd.read_csv('./data/data_clf.csv').drop(columns='Unnamed: 0')

This dataset is about Epileptic Seizure Recognition. Your data is brain activity (EEG signals) for 26 seconds. Is't really important to learn predict such things like epileptic. Maybe in future or right now machine learning algorithms help doctors make his work better and save more lives. Values which you predict

2 - They recorder the EEG from the area where the tumor was located 

1 - Recording of seizure activity 

In [3]:
X = df.drop(columns='y').values
y = df['y'].values

In [4]:
#only two classes
X = X[np.where((y == 2) | (y == 1))]
y = y[np.where((y == 2) | (y == 1))]
y[y==2] = 0

In [5]:
print("X shape: ", X.shape)
X[:5]

X shape:  (4600, 178)


array([[  386,   382,   356,   331,   320,   315,   307,   272,   244,
          232,   237,   258,   212,     2,  -267,  -605,  -850, -1001,
        -1109, -1090,  -967,  -746,  -464,  -152,   118,   318,   427,
          473,   485,   447,   397,   339,   312,   314,   326,   335,
          332,   324,   310,   312,   309,   309,   303,   297,   295,
          295,   293,   286,   279,   283,   301,   308,   285,   252,
          215,   194,   169,   111,   -74,  -388,  -679,  -892,  -949,
         -972, -1001, -1006,  -949,  -847,  -668,  -432,  -153,    72,
          226,   326,   392,   461,   495,   513,   511,   496,   479,
          453,   440,   427,   414,   399,   385,   385,   404,   432,
          444,   437,   418,   392,   373,   363,   365,   372,   385,
          388,   383,   371,   360,   353,   334,   303,   252,   200,
          153,   151,   143,    48,  -206,  -548,  -859, -1067, -1069,
         -957,  -780,  -597,  -460,  -357,  -276,  -224,  -210,  -350,
      

In [6]:
print("y shape: ", y.shape)
y[:5]

y shape:  (4600,)


array([1, 0, 1, 1, 0])

# Train / Test Split

In [7]:
# import train_test_split function to split the sample
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.5,    
                                                    random_state=123) 

# Random Forest

##### Let' s start with small steps

##### First step

Implement auxiliary function , which generate random subsample (with replacement) of X, y of size N with m features (m <= X.shape[1]) 

In [8]:
def gen_subsample(X, y, N, m):
    pass

##### Second step

Implement auxiliary function, which generate K random subsamples (with replacement) of X, y of size N with m random features (m <= X.shape[1])

In [9]:
def gen_subsamples(X, y, K, N, m):
    pass

#### Third step

Implement auxiliary function which get list of (X,y) with lengh K and fit K base_estimators. Each estimator fit from the corresponding sample. 

In [10]:
def fit_subsamples(subsamples, base_estimator):
    pass

### Example with multiprocessing

In [11]:
def fit(data):
    from sklearn.linear_model import LogisticRegression
    X, y = data
    return LogisticRegression().fit(X, y)

In [12]:
import multiprocessing


process_count = 4
parts = [
    (X, y)
    for i in range(process_count)
]

with multiprocessing.Pool(process_count) as p:
    # every part is sent to separate processes
    clfs = p.map(fit, parts)
clfs

[LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
           penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
           verbose=0, warm_start=False),
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
           penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
           verbose=0, warm_start=False),
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
           penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
           verbose=0, warm_start=False),
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
           penalty='l2', random_state

#### Fourth step 

Write code to generate two subsamples of data and fit 2 DecisionTreeClassifier parallel

### And now combine it all together in one class

# Task 1 (5 points)

Implement Random Forest classifier as it was described in your lectures:

**Input**: 
* training dataset $TDS=\{(x_{i},y_{i}),\,1=1,2,...N\}$; 
* the number of trees $B$ and the size of feature subsets $m$.

for $b=1,2,...B$:

1. generate random training dataset $TDS^{b}$ of size $N$ by sampling $(x_{i},y_{i})$ pairs from $TDS$ with replacement (bootstrap)
2. build a tree using $TDS^{b}$ training dataset with feature selection for each node from random subset of features of size $m$ (generated **individually for each node**).


**Output**: $B$ trees. Classification is done using majority vote and regression using averaging of $B$ outputs

**Hints:**
- Use decision tree classifier from sklean library. You can import it with the command: `from sklearn.tree import DecisionTreeClassifier`
- You can use `numpy.random.choice()` function to generate random subsamples to train decition tree classifiers.

# Task 2 (3 points)

Implement parallel learning of trees

Compare the running times of parallel and regular versions.

Use parameter n_jobs in RandomForestCalssifier init_function. Default value is 1 (if n_jobs = 1 run the regular version)

In [13]:
# You need to modify this class #

class RandomForestCalssifier(object):
    
    def __init__(self, n_trees=10, n_subset_features=2, n_jobs=1): # you can add more hyperparameters
        """
        This is your random forest classifier.
        
        Parameters
        ----------
        n_trees : int
            Number of decision trees to train.
        n_subset_features : int
            Number of random features to used to train a decision tree.
        n_jobs : int
            Number of jobs
        """
        
        self.n_trees = n_trees
        self.n_subset_features = n_subset_features
        
    def fit(self, X, y):
        """
        Fit the classifier.
        
        Parameters
        ----------
        X : numpy.array, shape = (n_objects, n_features)
            Matrix of objects that are described by their input features.
        y : numpy.array, shape = (n_objects)
            1D array with the object labels. 
            For the classification labels are integers in {0, 1, 2, ...}.
        """
        
        pass
    
    
    def predict_proba(self, X):
        """
        This methods performs probabilities prediction for new objects.
        
        Parameters
        ----------
        X : numpy.array, shape = (n_objects, n_features)
            Matrix of objects that are described by their input features.
            
        Returns
        -------
        proba : numpy.array, shape = (n_objects, n_classes)
            Array with predicted probabilities. 
        """
        
        proba = np.random.rand(len(X), 2) # for 2 classes
        
        return proba
    
    
    def predict(self, X):
        """
        This methods performs labels prediction for new objects.
        
        Parameters
        ----------
        X : numpy.array, shape = (n_objects, n_features)
            Matrix of objects that are described by their input features.
            
        Returns
        -------
        labels : numpy.array, shape = (n_objects)
            1D array with predicted labels. 
            For the classification labels are integers in {0, 1, 2, ...}.
        """
        
        labels = np.random.randint(low=0, high=2, size=len(X)) # for 2 classes
        
        return labels

# Task 3 (1 point)

Plot ROC curve on the test sample for your random forest classifier. Also, claculate ROC AUC value. Use `RandomForestClassifier.predict_proba()` method.

Hints:
- You can use `sklearn.metrics.roc_curve` frunction to calculate ROC curve.
- `sklearn.metrics.roc_auc_score` function helps you to calculate ROC AUC value.

In [14]:
# Your code is here

# Task 4 (2 points)

Plot dependecy of ROC AUC value from number of trees (`n_trees`) in your random forest classifier.

In [15]:
# Your code is here

# Task 5 (2 points)

Plot dependecy of ROC AUC value from `n_subset_features` of your random forest classifier. Use `n_trees=100`.

In [16]:
# Your code is here

# Gradient Boosting

# Read  New Data

In [17]:
#data from here https://archive.ics.uci.edu/ml/datasets/YearPredictionMSD
df = pd.read_csv('./data/YearPredictionMSD.txt', sep = ',', header=None)

 Prediction of the release year of a song from audio features. Songs are mostly western, commercial tracks ranging from 1922 to 2011, with a peak in the year 2000s
 
 Why? Because it's cool

In [18]:
X = df.drop(columns = 0).values
y = df[0].values

In [19]:
y

array([2001, 2001, 2001, ..., 2006, 2006, 2005])

## Before doing

Implement function which calculate $z_i$ from gradient boosting alogirithm (minus gradient of loss function)

In [20]:
def calc_objective(r, y, loss = 'mse'):
    """
    Parameters
        ----------
        r : np.array
            value of f(x)
        y : np.array
            target
        loss : str
            loss function. Possible values : mse, hl, logloss
    """
    pass

Implement function which make one step of gradient boossting (fit new estimator)

In [24]:
def step(x, y, estimators, lr, loss = 'mse'):
    """
    Parameters
        ----------
        x : np.array
            features
        y : np.array
            target
        estimators : array of estimators
            first estimators, who have already been trained
        lr : float
            learning rate
        loss : str
            loss function. Possible values : mse, hl, logloss
    """
    pass

## Now use your knowledge and implement gradient boosting

# Task 6 (5 points)

Implement GradientBoostingRegressor as it was described in your lectures:

**Input**: training dataset $(x_{i},y_{i}),\,i=1,2,...N$; loss function $\mathcal{L}(f,y)$; learning rate $\nu$ and the number $M$ of successive additive approximations.

1. Fit initial approximation $f_{0}(x)$ (might be taken $f_{0}(x)\equiv0$)
2. For each step $m=1,2,...M$:

    1. calculate derivatives $z_{i}=-\frac{\partial\mathcal{L}(r,y_{i})}{\partial r}|_{r=f^{m-1}(x_{i})}$
    2. fit $h_{m}$ to $\{(x_{i},z_{i})\}_{i=1}^{N}$, for example by solving
$$
\sum_{n=1}^{N}(h_{m}(x_{n})-z_{n})^{2}\to\min_{h_{m}}
$$
    4. set $f_{m}(x)=f_{m-1}(x)+\nu h_{m}(x)$


**Output**: approximation function $f_{M}(x)=f_{0}(x)+\sum_{m=1}^{M}\nu h_{m}(x)$

Implement three loss:

    1 MSE
    2 Huber loss(https://en.wikipedia.org/wiki/Huber_loss)
    3 log_loss (in this case we solve classification task
In our case $h_m$ is DecisionTreeRegressor

In [22]:
from sklearn.tree import DecisionTreeRegressor

In [23]:
# You need to modify this class #

class GradientBoostingRegressor(object):

    def __init__(self, n_estimators = 100, loss = 'mse', learning_rate=0.1):
        """
        This is your random forest classifier.
        
        Parameters
        ----------
        n_estimators : int
            Number of estimators to train.
        learning_rate : float
            earning_rate.
        loss : str
            Loss. Possible values : mse, hl, logloss
        """
        self.n_estimators = n_estimators
        self.learning_rate = learning_rate
    
    def fit(self, X, y):
        """
        Fit the classifier.
        
        Parameters
        ----------
        X : numpy.array, shape = (n_objects, n_features)
            Matrix of objects that are described by their input features.
        y : numpy.array, shape = (n_objects)
            1D array with the object labels. 
            For the classification labels are integers in {0, 1, 2, ...}.
        """
        
        pass
            
    def predict(self, X):
        """
        This methods performs labels prediction for new objects.
        
        Parameters
        ----------
        X : numpy.array, shape = (n_objects, n_features)
            Matrix of objects that are described by their input features.
            
        Returns
        -------
        labels : numpy.array, shape = (n_objects)
            1D array with predicted labels. 
            For the classification labels are integers in {0, 1, 2, ...}.
        """
        pass
    
    def predict_proba(self, X):
        """
        This methods performs probabilities prediction for new objects.
        
        Parameters
        ----------
        X : numpy.array, shape = (n_objects, n_features)
            Matrix of objects that are described by their input features.
            
        Returns
        -------
        proba : numpy.array, shape = (n_objects, n_classes)
            Array with predicted probabilities. 
        """
        pass
    
    def predict_top_n(self, X, n):
        """
        Predict only from top_n estimators 
        """
        pass
    
    def predict_proba_top_n(self, X, n):
        """
        Predict probability only from top_n estimators 
        """
        pass

# Task 7 (2 points)

Split your data on train, valid sample (fix random_seed = 42). Choose the optimal learning_rate and n_estimators (for logloss use data from first task)

# Task 8 (2 points)
Plot dependecy of loss value (in classification task plor roc-auc score) from `n_estimators` of your bossting. Use `learning_rate=0.1`.

# Task 9 (2 points)
Plot dependecy of loss value (in classification task plor roc-auc score) from `learning_rate` of your bossting. Use `n_estimators=100`.